### ISSUE TITLE
Request for additional API functions

### ISSUE THREAD

**Issue by aggieslaughter** [LabVIEW-DCAF/MotionModule#46]
The 'moves' folder in WordManipulation is awesome - would be nice if we could add a few other functions in a similar fashion. Those include:

Stop
Home
Config Homing (looks like the 402 standard supports multiple homing schemas)

**Comment by SimonRPSM** [comment]
Hey @aggieslaughter 

For the Stop command, would you want something different than the QuickStop implementation? 
When using the Controlword to call for a QuickStop, it calls the Class' Stop Method and goes to Quick Stop Active. I was going to wait until the Stop was "done" and then allow you to go back to Op Enable (At the time of writing this, calling the stop stops the axis but does not tell you when the stopping is done yet)

The QuickStop takes parameters from the Parameters_Build_Stop utility. 

For the Home, you would use the Controlword_ModeSpecific_ReferenceMove, and the Parameters_Build_reference to set the homing configuration. Would you be needing to "set" the configuration into the module and then call it separately?
