### ISSUE TITLE
Create VI Package

### ISSUE THREAD

**Issue by SimonRPSM** [LabVIEW-DCAF/MotionModule#48]
Now that some Unit Tests have been built, I can go ahead and start building VI Packages. 

This issue would require:
A) Use VI Package to build package
B) Include Jenkins file to allow for auto-build
C) Work with @pollockm to set up test machine that would be able to test this module.

**Comment by pollockm** [comment]
@SimonRPSM  - Just added LV 2015, 2016, 2017 build machines.  What software stack do you need to build your module?

**Comment by SimonRPSM** [comment]
@pollockm 
I would need Softmotion 2017 (as well as RT, dont know if that's part of the basic install)

**Comment by SimonRPSM** [comment]
After working with @pollockm we got the Motion Module into the Jenkins system.

**Comment by pollockm** [comment]
🎉
