### ISSUE TITLE
Unit tests hang build server

### ISSUE THREAD

**Issue by pollockm** [LabVIEW-DCAF/MotionModule#49]
![image](https://user-images.githubusercontent.com/5288961/31293240-2f2f2a60-aa9c-11e7-8bf5-892d731f8f3a.png)

**Comment by SimonRPSM** [comment]
May need to talk with Karl on this.

**Comment by pollockm** [comment]
This modal dialog box did not recur after clearing on one build, but it may come back if the target gets rebooted or reconfigured.

**Comment by SimonRPSM** [comment]
I discussed with Karl this, and he has some code that may be of help to deal with this if this happens again.

**Comment by SimonRPSM** [comment]
This issue has not been happening in quite a while - the build server is able to build as expected, so I will close this issue for now.
