### ISSUE TITLE
Results array empty 

### ISSUE THREAD

**Issue by aggieslaughter** [LabVIEW-DCAF/MotionModule#50]
Not getting data into the results array when I have a single axis in the project - even when setting the 'read bit' (bit 11).

**Comment by SimonRPSM** [comment]
Yep, just realized that when building the Result Array for a single axis I am checking the size of the Axis Array. Because this array is empty in that situation I need to add the single axis case.

**Comment by SimonRPSM** [comment]
Forgot to close this issue. PR #51 fixes this.
