### ISSUE TITLE
Issue in Read Fast VI

### ISSUE THREAD

**Issue by aggieslaughter** [LabVIEW-DCAF/MotionModule#74]
Was seeing a 0 velocity out of the read fast on my end. I looked into the Read Fast VI (this is all while doing a velocity move) - and saw that it was reading the 'Velocity Setpoint'.

I tried to switch that to 'velocity readback' and it returns the velocity as expected. Not sure why setpoint is showing 0 - perhaps something to do with how velocity moves are done - but the velocity readback seems to always give the correct value. 

Any idea why velocity setpoint is always returning 0 though?

**Comment by SimonRPSM** [comment]
Hey there, @aggieslaughter ;

The Velocity Setpoint only is reported by Softmotion under some move types. You'll see it as zero if you make a position move or velocity move but it will be nonzero, if memory serves, when you force a specific velocity setpoint. 

I added it for symmetry with the position method, but I can remove it for now if necessary.

**Comment by SimonRPSM** [comment]
To avoid confusion, I'm making both Read Fast methods into the Feedback ones.
