### ISSUE TITLE
Getting Started Experience - Simple Sequencer and move examples

### ISSUE THREAD

**Issue by SimonRPSM** [LabVIEW-DCAF/MotionModule#8]
The Sample sequencer included with the module does not take the internal state machine through the correct states. 

Need to troubleshoot and fix it. 

EDIT: 

- Sample sequencer demonstrating how to start up the module
- Sample project that works on a Simulated Axis (cleanup of the Runtime example possibly)
- Basic demo on how to do a Position Move
- Basic Demo on how to do a Reference Move.

**Comment by aggieslaughter** [comment]
A basic example of the things required to get a drive from the initial fault/power-on state through 'operational' would be very helpful. Perhaps with examples for the different move types (absolute, relative)?

**Comment by SimonRPSM** [comment]
Sounds good. I'll be rescoping this issue to, instead of it being about "fixing" an example I had, to look into the getting started experience with the module at large. 

Check out Edit to the beggining post.
