### ISSUE TITLE
Motion buffering/blending issue

### ISSUE THREAD

**Issue by aggieslaughter** [LabVIEW-DCAF/MotionModule#80]
The bit 5 is now getting checked in the Profile Position Mode case - but it's not being used as an input to the 'immediate' input of the move VI. Connecting the 'immediate' LED to the front panel and connecting the output of the "parse bit 5" seems to cause things to work perfectly in my sequencer.

**Comment by aggieslaughter** [comment]
![capture](https://user-images.githubusercontent.com/1827554/33622464-82dbb912-d9b3-11e7-9469-ff39301b3da1.PNG)

**Comment by SimonRPSM** [comment]
Yep, seems like I forgot to connect it - sorry about that! It's hard to test with a single axis because blends are less obvious.
